#!name=WLOC Location Modification
#!desc=Modify the coordinates returned by Apple's network‑location services (Wi‑Fi, cellular base stations) to achieve network‑level virtual location on iOS.
#!author=abcpeak Rewrite
#!homepage=https://github.com/abcpeak/wloc

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/abcpeak/wloc/refs/heads/main/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/abcpeak/wloc/refs/heads/main/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com, gsp-ssl.ls.apple.com, bluedot.is.autonavi.com, bluedot.is.autonavi.com.gds.alibabadns.com